name: Continuous Deployment
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure
      run: npm install
    - name: Build
      run: npm run build
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [integration-tests]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
